import{matchLines,normalize}from'./catalog-client.js?v=25';
import{extractCardCandidates,rerankByCardImage}from'./card-vision.js?v=1';
const waitEvent=(el,name)=>new Promise((resolve,reject)=>{const ok=()=>{cleanup();resolve()},bad=()=>{cleanup();reject(new Error(`Video ${name} failed.`))},cleanup=()=>{el.removeEventListener(name,ok);el.removeEventListener('error',bad)};el.addEventListener(name,ok,{once:true});el.addEventListener('error',bad,{once:true})});
async function seek(video,time){if(Math.abs(video.currentTime-time)<.025)return;video.currentTime=time;await waitEvent(video,'seeked')}
function frameCanvas(video,maxWidth=900){const scale=Math.min(1,maxWidth/video.videoWidth),canvas=document.createElement('canvas');canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);canvas.getContext('2d',{willReadFrequently:true}).drawImage(video,0,0,canvas.width,canvas.height);return canvas}
function crop(canvas,x,y,w,h,width=1000){const out=document.createElement('canvas'),height=Math.round(width*h/w);out.width=width;out.height=height;const ctx=out.getContext('2d');ctx.filter='contrast(1.22) saturate(.78)';ctx.drawImage(canvas,Math.round(canvas.width*x),Math.round(canvas.height*y),Math.round(canvas.width*w),Math.round(canvas.height*h),0,0,width,height);return out}
function contextCrop(canvas){return crop(canvas,.03,.08,.94,.76,1000)}
function cardRegion(canvas){const portrait=canvas.height>canvas.width;return crop(canvas,portrait?.16:.06,portrait?.18:.06,portrait?.68:.88,portrait?.48:.86,320)}
function frameMetrics(canvas){const sample=cardRegion(canvas),tiny=document.createElement('canvas');tiny.width=32;tiny.height=32;const ctx=tiny.getContext('2d',{willReadFrequently:true});ctx.drawImage(sample,0,0,32,32);const pixels=ctx.getImageData(0,0,32,32).data,signature=new Uint8Array(256);let sharpness=0,p=0;for(let y=0;y<32;y+=2)for(let x=0;x<32;x+=2){const i=(y*32+x)*4,v=Math.round(pixels[i]*.299+pixels[i+1]*.587+pixels[i+2]*.114);signature[p++]=v;if(x>0)sharpness+=Math.abs(v-signature[p-2]);if(y>0)sharpness+=Math.abs(v-signature[p-17])}return{signature,sharpness}}
function signatureDifference(a,b){if(!a||!b)return Infinity;let total=0;for(let i=0;i<a.length;i++)total+=Math.abs(a[i]-b[i]);return total/a.length}
async function selectCandidateFrames(video,duration,onProgress){const sampleStep=Math.max(.28,Math.min(.42,duration/90)),samples=[];for(let t=0;t<duration;t+=sampleStep){await seek(video,t);const metrics=frameMetrics(frameCanvas(video,720));samples.push({time:t,...metrics});onProgress({phase:`Finding card changes ${samples.length}`,value:Math.min(.1,t/duration*.1)})}const selected=[],bucketSize=1.5;for(let start=0;start<duration;start+=bucketSize){const bucket=samples.filter(sample=>sample.time>=start&&sample.time<start+bucketSize).sort((a,b)=>b.sharpness-a.sharpness);if(bucket[0])selected.push({...bucket[0],priority:1})}for(let i=1;i<samples.length;i++){const difference=signatureDifference(samples[i-1].signature,samples[i].signature);if(difference>=18){const around=samples.slice(Math.max(0,i-1),Math.min(samples.length,i+2)).sort((a,b)=>b.sharpness-a.sharpness)[0];selected.push({...around,priority:2+difference/100})}}const clustered=[];for(const pick of selected.sort((a,b)=>a.time-b.time)){const prior=clustered.at(-1);if(prior&&pick.time-prior.time<.58){if(pick.priority*pick.sharpness>prior.priority*prior.sharpness)clustered[clustered.length-1]=pick}else clustered.push(pick)}const limit=Math.max(18,Math.min(36,Math.ceil(duration*.82))),picks=clustered.length<=limit?clustered:clustered.map((pick,index)=>({...pick,index})).sort((a,b)=>b.priority-a.priority||b.sharpness-a.sharpness).slice(0,limit).sort((a,b)=>a.time-b.time),frames=[];for(let i=0;i<picks.length;i++){await seek(video,picks[i].time);frames.push({time:picks[i].time,canvas:frameCanvas(video,1080)});onProgress({phase:`Preparing key frame ${i+1} of ${picks.length}`,value:.1+(i+1)/picks.length*.04})}return frames}
function textBandSheet(canvas,bands){const out=document.createElement('canvas');out.width=800;out.height=bands.length*104;const ctx=out.getContext('2d');ctx.fillStyle='#000';ctx.fillRect(0,0,out.width,out.height);for(let i=0;i<bands.length;i++){const band=crop(canvas,.025,bands[i],.95,.082,1100),top=i*104;ctx.save();ctx.beginPath();ctx.rect(12,top+5,776,94);ctx.clip();ctx.translate(400,top+52);ctx.filter='grayscale(1) contrast(2.05)';const scale=Math.max(776/band.width,94/band.height);ctx.drawImage(band,-band.width*scale/2,-band.height*scale/2,band.width*scale,band.height*scale);ctx.restore()}return out}
function contextTextSheet(canvas){return textBandSheet(canvas,[.62,.66,.685,.72,.76])}
function cardTextSheet(canvas){const portrait=canvas.height>canvas.width,x=portrait?.16:.08,y=portrait?.18:.08,w=portrait?.68:.84,h=portrait?.48:.82,source=crop(canvas,x,y,w,h,760),bands=portrait?[.29,.32,.35,.38,.41,.44]:[],bandSheet=textBandSheet(canvas,bands),out=document.createElement('canvas'),angles=[0,-.12,.12];out.width=800;out.height=bandSheet.height+angles.length*300;const ctx=out.getContext('2d');ctx.fillStyle='#000';ctx.fillRect(0,0,out.width,out.height);ctx.drawImage(bandSheet,0,0);for(let i=0;i<angles.length;i++){ctx.save();ctx.translate(400,bandSheet.height+i*300+150);ctx.rotate(angles[i]);ctx.filter='contrast(1.55) saturate(.58)';const scale=Math.min(760/source.width,270/source.height);ctx.drawImage(source,-source.width*scale/2,-source.height*scale/2,source.width*scale,source.height*scale);ctx.restore()}return out}
function linesFromOcr(data,{expand=false}={}){const lines=(data.lines||[]).filter(x=>x.confidence>=15).map(x=>x.text.trim()).filter(Boolean),textLines=String(data.text||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);if(!expand)return[...new Set([...lines,...textLines])];const words=(data.words||[]).filter(x=>x.confidence>=12).map(x=>x.text.trim()).filter(x=>/[a-z]{2}/i.test(x)).slice(0,48),phrases=[];for(let size=2;size<=5;size++)for(let i=0;i+size<=words.length;i++)phrases.push(words.slice(i,i+size).join(' '));return[...new Set([...lines,...phrases,...textLines])].slice(0,180)}
const OCR_PREFIX_ALTS={0:['o'],o:['0'],1:['i','l'],i:['l','1'],l:['i','1'],5:['s'],s:['5'],8:['b'],b:['8'],c:['e'],e:['c'],t:['l'],m:['rn']};
function recognitionLines(lines){const originals=[...new Set(lines.map(x=>x.trim()).filter(Boolean))],out=new Set(originals);for(const raw of originals){const words=normalize(raw).split(' ').filter(Boolean);for(let wi=0;wi<words.length;wi++){const word=words[wi];if(word.length<2)continue;const variants=new Set([word]);for(const first of OCR_PREFIX_ALTS[word[0]]||[])variants.add(first+word.slice(1));for(const second of OCR_PREFIX_ALTS[word[1]]||[])variants.add(word[0]+second+word.slice(2));if(word.startsWith('rn'))variants.add('m'+word.slice(2));for(const variant of variants){if(variant===word)continue;const copy=[...words];copy[wi]=variant;out.add(copy.join(' '))}}}return[...out].slice(0,180)}
function mergeMatches(...lists){const best=new Map;for(const match of lists.flat()){const id=String(match.item.id),prior=best.get(id);if(!prior||match.score>prior.score)best.set(id,match)}return[...best.values()].sort((a,b)=>b.score-a.score)}
function priceFor(item,finish){if(!item||finish==='unknown')return null;const rows=item.p||[],usable=item.vf==='foil'?rows:rows.filter(x=>finish==='foil'?String(x.f).toLowerCase().includes('foil'):!String(x.f).toLowerCase().includes('foil'));const market=usable.map(x=>Number(x.m)).filter(Number.isFinite);return market.length?Math.max(...market):null}
function anyFinishAtLeast(item,floor=1){return(item?.p||[]).some(row=>Number.isFinite(Number(row.m))&&Number(row.m)>=floor)}
export function inferScope(rows){const games=new Map;for(const row of rows){const bestByGame=new Map;for(const match of(row.matches||[])){const prior=bestByGame.get(match.item.game);if(!prior||match.score>prior.score)bestByGame.set(match.item.game,match)}const ranked=[...bestByGame.values()].sort((a,b)=>b.score-a.score),top=ranked[0],runner=ranked[1];if(!top||top.score<.58)continue;const margin=top.score-(runner?.score||.45),entry=games.get(top.item.game)||{score:0,frames:0};entry.score+=Math.max(.05,top.score-.5)+Math.max(0,margin);entry.frames++;games.set(top.item.game,entry)}const ranked=[...games].sort((a,b)=>b[1].score-a[1].score||b[1].frames-a[1].frames),winner=ranked[0],runner=ranked[1];if(!winner||winner[1].frames<3)return{game:null,set:null};if(runner){const scoreLead=winner[1].score>=runner[1].score*1.08,frameLead=winner[1].frames>=runner[1].frames+2;if(!scoreLead&&!frameLead)return{game:null,set:null}}return{game:winner[0],set:null}}
function inferScopeFromHints(rows,index){const lines=rows.flatMap(row=>row.lines||[]).map(normalize).filter(x=>x.length>=4),scores=[];for(const entry of index?.games||[]){let score=0,bestSet=null;for(const term of entry.terms||[]){if(term.length<4)continue;for(const line of lines){if(line.includes(term)){const weight=Math.min(5,term.split(' ').length)+Math.min(2,term.length/18);if(weight>score){score=weight;bestSet=term}}}}if(score)scores.push({game:entry.game,set:bestSet,score})}scores.sort((a,b)=>b.score-a.score);return scores[0]&&(!scores[1]||scores[0].score>=scores[1].score+1)?{game:scores[0].game,set:scores[0].set}:null}
export function groupDetections(rows,{allowStrongSingles=false}={}){const active=new Map,groups=[];for(const row of [...rows].sort((a,b)=>a.time-b.time)){const key=row.match.item.k||row.match.item.n,prior=active.get(key);if(prior&&row.time-prior.lastTime<=2.6){prior.lastTime=row.time;prior.count++;prior.scoreTotal+=row.match.score;if(row.match.score>prior.match.score){prior.match=row.match;prior.cardCandidates=row.cardCandidates}}else{const group={key,time:row.time,lastTime:row.time,count:1,scoreTotal:row.match.score,match:row.match,cardCandidates:row.cardCandidates};active.set(key,group);groups.push(group)}}return groups.filter(g=>{const words=g.key.split(' ').length,avg=g.scoreTotal/g.count;if(words===1)return g.count>=2&&avg>=.88;return g.count>=2&&avg>=.62||allowStrongSingles&&g.count===1&&avg>=.9}).sort((a,b)=>a.time-b.time)}
async function recognizeFrames(frames,onProgress){const workerCount=Math.max(1,Math.min(3,Math.floor((navigator.hardwareConcurrency||4)/2),frames.length)),workers=await Promise.all(Array.from({length:workerCount},async()=>{const worker=await window.Tesseract.createWorker('eng',1);await worker.setParameters({tessedit_pageseg_mode:'11',preserve_interword_spaces:'1'});return worker})),results=new Array(frames.length);let next=0,done=0,contextLines=[];try{const contextResult=await workers[0].recognize(contextTextSheet(frames[Math.floor(frames.length/2)].canvas));contextLines=recognitionLines(linesFromOcr(contextResult.data,{expand:false}));onProgress({phase:'Reading stream context',value:.18});await Promise.all(workers.map(async worker=>{while(true){const index=next++;if(index>=frames.length)return;const cardCandidates=extractCardCandidates(frames[index].canvas),cardResult=await worker.recognize(cardTextSheet(frames[index].canvas)),cardLines=linesFromOcr(cardResult.data,{expand:true});frames[index].canvas.width=frames[index].canvas.height=1;results[index]={time:frames[index].time,lines:recognitionLines(cardLines),cardCandidates};done++;onProgress({phase:`Reading best card view ${done} of ${frames.length}`,value:.18+done/frames.length*.48})}}))}finally{await Promise.all(workers.map(worker=>worker.terminate()))}return{observations:results,contextLines}}
async function mapLimit(items,limit,task,onDone=()=>{}){const results=new Array(items.length);let next=0,done=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(true){const index=next++;if(index>=items.length)return;results[index]=await task(items[index],index);onDone(++done,items.length)}}));return results}
export async function analyzeVideo(video,{onProgress=()=>{}}={}){
  if(!window.Tesseract)throw new Error('Text recognition could not load. Check the connection and try again.');
  const duration=video.duration;if(!Number.isFinite(duration)||duration<=0)throw new Error('The selected video could not be read.');
  const frames=await selectCandidateFrames(video,duration,onProgress),recognition=await recognizeFrames(frames,onProgress),observations=recognition.observations;
  const scopeRows=observations.filter((_,i)=>i%Math.max(1,Math.floor(observations.length/8))===0).slice(0,8),scopeEvidence=[{lines:recognition.contextLines},...scopeRows],scopeIndex=await fetch('./catalog/scope.json').then(r=>r.ok?r.json():null).catch(()=>null),hintScope=inferScopeFromHints(scopeEvidence,scopeIndex);if(!hintScope)await mapLimit(scopeEvidence,3,async row=>{row.matches=row.lines.length?await matchLines(row.lines.slice(0,24),()=>{},{relaxed:true}):[]},(done,total)=>onProgress({phase:`Identifying card game ${done} of ${total}`,value:.66+done/total*.08}));
  const scope=hintScope||inferScope(scopeEvidence);if(!scope.game)throw new Error('The card game could not be identified confidently. Try a clearer clip with each card held briefly in view.');
  await mapLimit(observations,4,async row=>{row.matches=row.lines.length?await matchLines(row.lines,()=>{},{game:scope.game,relaxed:true}):[]},(done,total)=>onProgress({phase:`Matching ${scope.game} cards ${done} of ${total}`,value:.76+done/total*.12}));
  const selectedGame=scope.game,detections=[];
  for(let i=0;i<observations.length;i++){
    const row=observations[i],matches=row.matches;
    if(matches[0]){const byName=new Map;for(const match of matches){const key=match.item.k||match.item.n,prior=byName.get(key);if(!prior||match.score>prior.score)byName.set(key,match)}const ranked=[...byName.values()].sort((a,b)=>b.score-a.score),top=ranked[0],runner=ranked[1],margin=top.score-(runner?.score||0);if(top.score>=.72&&(margin>=.06||top.score>=.9)){const key=top.item.k||top.item.n,alternatives=matches.filter(x=>(x.item.k||x.item.n)===key&&x.score>=top.score-.08).slice(0,12).map(x=>x.item);detections.push({time:row.time,cardCandidates:row.cardCandidates,match:{...top,alternatives}})}}
  }
  const groups=groupDetections(detections,{allowStrongSingles:true}).filter(g=>(g.match.alternatives||[g.match.item]).some(item=>anyFinishAtLeast(item))),hits=[];
  for(let i=0;i<groups.length;i++){const g=groups[i],textCandidates=g.match.alternatives||[g.match.item],visualMatches=await rerankByCardImage(g.cardCandidates,textCandidates.map(item=>({item,score:g.match.score}))),candidates=visualMatches.map(match=>match.item),chosen=candidates.find(x=>x.vf!=='foil')||candidates[0]||g.match.item,price=priceFor(chosen,'nonfoil'),identityConfidence=visualMatches[0]?.score||g.match.score,identityAmbiguous=new Set(candidates.map(x=>`${x.game}|${x.set}|${x.printing||''}`)).size>1,specialFinishOnly=(price===null||price<1)&&candidates.some(item=>anyFinishAtLeast(item));hits.push({id:crypto.randomUUID(),time:g.time,name:(chosen.name||'').replace(/\s*\(foil\)\s*$/i,''),game:chosen.game,set:chosen.set,printing:chosen.printing||'',productId:chosen.id,finish:'nonfoil',finishConfidence:1,foilScore:null,price,identityConfidence,identityAmbiguous,confirmed:identityConfidence>=.9&&!identityAmbiguous&&!specialFinishOnly&&price!==null&&price>=1,skipped:false,candidates});onProgress({phase:`Verifying distinct card ${i+1} of ${groups.length}`,value:.88+(i+1)/Math.max(1,groups.length)*.12})}
  onProgress({phase:'Analysis complete',value:1});await seek(video,0);return{hits,frames:frames.length,detections:detections.length,selectedGame,selectedSet:null};
}
