import{matchLines}from'./catalog-client.js';
const waitEvent=(el,name)=>new Promise((resolve,reject)=>{const ok=()=>{cleanup();resolve()},bad=()=>{cleanup();reject(new Error(`Video ${name} failed.`))},cleanup=()=>{el.removeEventListener(name,ok);el.removeEventListener('error',bad)};el.addEventListener(name,ok,{once:true});el.addEventListener('error',bad,{once:true})});
async function seek(video,time){if(Math.abs(video.currentTime-time)<.025)return;video.currentTime=time;await waitEvent(video,'seeked')}
function frameCanvas(video,maxWidth=960){const scale=Math.min(1,maxWidth/video.videoWidth),canvas=document.createElement('canvas');canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);canvas.getContext('2d',{willReadFrequently:true}).drawImage(video,0,0,canvas.width,canvas.height);return canvas}
function ocrCrop(canvas){const out=document.createElement('canvas');out.width=canvas.width;out.height=Math.round(canvas.height*.72);out.getContext('2d').drawImage(canvas,0,Math.round(canvas.height*.05),canvas.width,out.height,0,0,out.width,out.height);return out}
function linesFromOcr(data){const lines=(data.lines||[]).filter(x=>x.confidence>=34).map(x=>x.text.trim()).filter(Boolean);return lines.length?lines:String(data.text||'').split(/\n+/).map(x=>x.trim()).filter(Boolean)}
function pixelSignature(canvas){const ctx=canvas.getContext('2d',{willReadFrequently:true}),{data}=ctx.getImageData(Math.round(canvas.width*.15),Math.round(canvas.height*.15),Math.round(canvas.width*.7),Math.round(canvas.height*.7));let bright=0,colorful=0,sum=0,count=0;for(let i=0;i<data.length;i+=16){const r=data[i],g=data[i+1],b=data[i+2],hi=Math.max(r,g,b),lo=Math.min(r,g,b);bright+=hi>238&&hi-lo>18;colorful+=hi-lo>55;sum+=hi;count++}return{bright:bright/count,color:colorful/count,luma:sum/count}}
async function finishEvidence(video,time){const samples=[];for(const offset of[-.35,-.15,.05,.25,.45]){await seek(video,Math.max(0,Math.min(video.duration-.02,time+offset)));samples.push(pixelSignature(frameCanvas(video,360)))}const b=samples.map(x=>x.bright),l=samples.map(x=>x.luma),range=Math.max(...b)-Math.min(...b),lRange=Math.max(...l)-Math.min(...l),avg=b.reduce((a,x)=>a+x,0)/b.length;const foilScore=Math.min(1,range*9+lRange/80+avg*1.8);return{foilScore,samples}}
function selectFinish(candidates,evidence){const hasFoil=candidates.some(x=>x.vf==='foil'||(x.p||[]).some(p=>String(p.f).toLowerCase().includes('foil'))),hasNormal=candidates.some(x=>x.vf!=='foil');if(hasFoil&&!hasNormal)return{finish:'foil',confidence:.96};if(hasNormal&&!hasFoil)return{finish:'nonfoil',confidence:.96};if(evidence.foilScore>=.72)return{finish:'foil',confidence:evidence.foilScore};if(evidence.foilScore<=.24)return{finish:'nonfoil',confidence:1-evidence.foilScore};return{finish:'unknown',confidence:1-Math.abs(.5-evidence.foilScore)*2}}
function priceFor(item,finish){if(!item||finish==='unknown')return null;const rows=item.p||[],usable=item.vf==='foil'?rows:rows.filter(x=>finish==='foil'?String(x.f).toLowerCase().includes('foil'):!String(x.f).toLowerCase().includes('foil'));const market=usable.map(x=>Number(x.m)).filter(Number.isFinite);return market.length?Math.max(...market):null}
function groupDetections(rows){const groups=[];for(const row of rows.sort((a,b)=>a.time-b.time)){const key=row.match.item.k||row.match.item.n,last=groups.at(-1);if(last&&last.key===key&&row.time-last.lastTime<3.2){last.lastTime=row.time;if(row.match.score>last.match.score)last.match=row.match}else groups.push({key,time:row.time,lastTime:row.time,match:row.match})}return groups}
export async function analyzeVideo(video,{onProgress=()=>{}}={}){if(!window.Tesseract)throw new Error('Text recognition could not load. Check the connection and try again.');const duration=video.duration;if(!Number.isFinite(duration)||duration<=0)throw new Error('The selected video could not be read.');const interval=Math.max(.65,duration/180),times=[];for(let t=0;t<duration;t+=interval)times.push(t);const worker=await window.Tesseract.createWorker('eng',1,{logger:m=>{if(m.status==='recognizing text')onProgress({phase:'Reading cards',value:(m.progress||0)*.7})}});const detections=[];try{for(let i=0;i<times.length;i++){await seek(video,times[i]);const frame=frameCanvas(video);const result=await worker.recognize(ocrCrop(frame));const lines=linesFromOcr(result.data);if(lines.length){const matches=await matchLines(lines);if(matches[0]?.score>=.72){const top=matches[0],alternatives=matches.filter(x=>(x.item.k||x.item.n)===(top.item.k||top.item.n)&&x.score>=top.score-.08).slice(0,12).map(x=>x.item);detections.push({time:times[i],match:{...top,alternatives}})}}onProgress({phase:`Reading frame ${i+1} of ${times.length}`,value:(i+1)/times.length*.72})}}finally{await worker.terminate()}
  const groups=groupDetections(detections),hits=[];for(let i=0;i<groups.length;i++){const g=groups[i],candidates=g.match.alternatives||[g.match.item],evidence=await finishEvidence(video,g.time),finish=selectFinish(candidates,evidence),chosen=candidates.find(x=>finish.finish==='foil'?x.vf==='foil':x.vf!=='foil')||g.match.item,price=priceFor(chosen,finish.finish),identityConfidence=g.match.score,identityAmbiguous=new Set(candidates.map(x=>`${x.game}|${x.set}|${x.printing||''}`)).size>1;hits.push({id:crypto.randomUUID(),time:g.time,name:(chosen.name||'').replace(/\s*\(foil\)\s*$/i,''),game:chosen.game,set:chosen.set,printing:chosen.printing||'',productId:chosen.id,finish:finish.finish,finishConfidence:finish.confidence,foilScore:evidence.foilScore,price,identityConfidence,identityAmbiguous,confirmed:identityConfidence>=.9&&!identityAmbiguous&&finish.finish!=='unknown'&&price!==null,skipped:false,candidates});onProgress({phase:`Checking finish ${i+1} of ${groups.length}`,value:.72+(i+1)/Math.max(1,groups.length)*.28})}await seek(video,0);return{hits,frames:times.length,detections:detections.length}}
