import{matchLines,normalize}from'./catalog-client.js?v=25';
import{extractCardRegions,matchCardArtwork,rerankByCardImage}from'./card-vision.js?v=6';
import{artworkFeatures}from'./feature-matcher.js?v=1';
const waitEvent=(el,name)=>new Promise((resolve,reject)=>{const ok=()=>{cleanup();resolve()},bad=()=>{cleanup();reject(new Error(`Video ${name} failed.`))},cleanup=()=>{el.removeEventListener(name,ok);el.removeEventListener('error',bad)};el.addEventListener(name,ok,{once:true});el.addEventListener('error',bad,{once:true})});
async function seek(video,time){if(Math.abs(video.currentTime-time)<.025)return;video.currentTime=time;await waitEvent(video,'seeked')}
function frameCanvas(video,maxWidth=900){const scale=Math.min(1,maxWidth/video.videoWidth),canvas=document.createElement('canvas');canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);canvas.getContext('2d',{willReadFrequently:true}).drawImage(video,0,0,canvas.width,canvas.height);return canvas}
function frameMetrics(canvas){const sample=extractCardRegions(canvas)[0]?.canvas;if(!sample)return{signature:null,sharpness:0};const tiny=document.createElement('canvas');tiny.width=32;tiny.height=32;const ctx=tiny.getContext('2d',{willReadFrequently:true});ctx.drawImage(sample,0,0,32,32);const pixels=ctx.getImageData(0,0,32,32).data,signature=new Uint8Array(256);let sharpness=0,p=0;for(let y=0;y<32;y+=2)for(let x=0;x<32;x+=2){const i=(y*32+x)*4,v=Math.round(pixels[i]*.299+pixels[i+1]*.587+pixels[i+2]*.114);signature[p++]=v;if(x>0)sharpness+=Math.abs(v-signature[p-2]);if(y>0)sharpness+=Math.abs(v-signature[p-17])}return{signature,sharpness}}
function signatureDifference(a,b){if(!a||!b)return Infinity;let total=0;for(let i=0;i<a.length;i++)total+=Math.abs(a[i]-b[i]);return total/a.length}
async function selectCandidateFrames(video,duration,onProgress){const sampleStep=Math.max(.28,Math.min(.42,duration/90)),samples=[];for(let t=0;t<duration;t+=sampleStep){await seek(video,t);const metrics=frameMetrics(frameCanvas(video,720));samples.push({time:t,...metrics});onProgress({phase:`Finding card changes ${samples.length}`,value:Math.min(.1,t/duration*.1)})}const selected=[],bucketSize=1.5;for(let start=0;start<duration;start+=bucketSize){const bucket=samples.filter(sample=>sample.time>=start&&sample.time<start+bucketSize).sort((a,b)=>b.sharpness-a.sharpness);if(bucket[0])selected.push({...bucket[0],priority:1})}for(let i=1;i<samples.length;i++){const difference=signatureDifference(samples[i-1].signature,samples[i].signature);if(difference>=18){const around=samples.slice(Math.max(0,i-1),Math.min(samples.length,i+2)).sort((a,b)=>b.sharpness-a.sharpness)[0];selected.push({...around,priority:2+difference/100})}}const clustered=[];for(const pick of selected.sort((a,b)=>a.time-b.time)){const prior=clustered.at(-1);if(prior&&pick.time-prior.time<.58){if(pick.priority*pick.sharpness>prior.priority*prior.sharpness)clustered[clustered.length-1]=pick}else clustered.push(pick)}const limit=Math.max(18,Math.min(36,Math.ceil(duration*.82))),picks=clustered.length<=limit?clustered:clustered.map((pick,index)=>({...pick,index})).sort((a,b)=>b.priority-a.priority||b.sharpness-a.sharpness).slice(0,limit).sort((a,b)=>a.time-b.time),frames=[];for(let i=0;i<picks.length;i++){await seek(video,picks[i].time);frames.push({time:picks[i].time,canvas:frameCanvas(video,1080)});onProgress({phase:`Preparing key frame ${i+1} of ${picks.length}`,value:.1+(i+1)/picks.length*.04})}return frames}
function cardTextSheet(regions){const cards=regions.slice(0,6),bands=[.12,.18,.25],rowHeight=330,out=document.createElement('canvas');out.width=900;out.height=Math.max(120,cards.length*rowHeight);const ctx=out.getContext('2d');ctx.fillStyle='#000';ctx.fillRect(0,0,out.width,out.height);
  // Recognition sees only detector-isolated card candidates. Never copy a raw
  // frame or a broad reveal-area crop here: stream titles, seller UI, phone
  // chrome and background products must not be allowed into OCR or matching.
  for(let i=0;i<cards.length;i++){const card=cards[i].canvas,top=i*rowHeight;for(let band=0;band<bands.length;band++){const titleHeight=Math.max(1,Math.round(card.height*bands[band])),y=top+8+band*96;ctx.save();ctx.beginPath();ctx.rect(10,y,880,88);ctx.clip();ctx.filter='grayscale(1) contrast(2.25)';ctx.drawImage(card,0,0,card.width,titleHeight,10,y,880,88);ctx.restore()}ctx.save();ctx.beginPath();ctx.rect(230,top+298,440,26);ctx.clip();ctx.filter='grayscale(1) contrast(1.65)';ctx.drawImage(card,0,0,card.width,card.height,230,top+298,440,Math.min(26,card.height*440/card.width));ctx.restore()}return out}
function linesFromOcr(data,{expand=false}={}){const lines=(data.lines||[]).filter(x=>x.confidence>=15).map(x=>x.text.trim()).filter(Boolean),textLines=String(data.text||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);if(!expand)return[...new Set([...lines,...textLines])];const words=(data.words||[]).filter(x=>x.confidence>=12).map(x=>x.text.trim()).filter(x=>/[a-z]{2}/i.test(x)).slice(0,48),phrases=[];for(let size=2;size<=5;size++)for(let i=0;i+size<=words.length;i++)phrases.push(words.slice(i,i+size).join(' '));return[...new Set([...lines,...phrases,...textLines])].slice(0,180)}
const OCR_PREFIX_ALTS={0:['o'],o:['0'],1:['i','l'],i:['l','1'],l:['i','1'],5:['s'],s:['5'],8:['b'],b:['8'],c:['e'],e:['c'],t:['l'],m:['rn']};
function recognitionLines(lines){const originals=[...new Set(lines.map(x=>x.trim()).filter(Boolean))],out=new Set(originals);for(const raw of originals){const words=normalize(raw).split(' ').filter(Boolean);for(let wi=0;wi<words.length;wi++){const word=words[wi];if(word.length<2)continue;const variants=new Set([word]);for(const first of OCR_PREFIX_ALTS[word[0]]||[])variants.add(first+word.slice(1));for(const second of OCR_PREFIX_ALTS[word[1]]||[])variants.add(word[0]+second+word.slice(2));if(word.startsWith('rn'))variants.add('m'+word.slice(2));for(const variant of variants){if(variant===word)continue;const copy=[...words];copy[wi]=variant;out.add(copy.join(' '))}}}return[...out].slice(0,180)}
function priceFor(item,finish){if(!item||finish==='unknown')return null;const rows=item.p||[],usable=item.vf==='foil'?rows:rows.filter(x=>finish==='foil'?String(x.f).toLowerCase().includes('foil'):!String(x.f).toLowerCase().includes('foil'));const market=usable.map(x=>Number(x.m)).filter(Number.isFinite);return market.length?Math.max(...market):null}
function anyFinishAtLeast(item,floor=1){return(item?.p||[]).some(row=>Number.isFinite(Number(row.m))&&Number(row.m)>=floor)}
export function cardIdentityName(item){return normalize(String(item?.name||item?.k||item?.n||'').replace(/\s*\([^)]*\)/g,' '))}
export function groupDetections(rows,{allowStrongSingles=false}={}){const active=new Map,groups=[];for(const row of [...rows].sort((a,b)=>a.time-b.time)){const name=cardIdentityName(row.match.item),key=`${row.match.item.game}|${name}`,prior=active.get(key);if(prior&&row.time-prior.lastTime<=2.6){prior.lastTime=row.time;prior.count++;prior.scoreTotal+=row.match.score;if(row.match.score>prior.match.score){prior.match=row.match;prior.cardCandidates=row.cardCandidates}}else{const group={key,time:row.time,lastTime:row.time,count:1,scoreTotal:row.match.score,match:row.match,cardCandidates:row.cardCandidates};active.set(key,group);groups.push(group)}}return groups.filter(g=>{const words=cardIdentityName(g.match.item).split(' ').length,avg=g.scoreTotal/g.count;if(words===1)return g.count>=2&&avg>=.88;return g.count>=2&&avg>=.62||allowStrongSingles&&g.count===1&&avg>=.9}).sort((a,b)=>a.time-b.time)}
async function recognizeFrames(frames,onProgress){const workerCount=Math.max(1,Math.min(3,Math.floor((navigator.hardwareConcurrency||4)/2),frames.length)),workers=await Promise.all(Array.from({length:workerCount},async()=>{const worker=await window.Tesseract.createWorker('eng',1);await worker.setParameters({tessedit_pageseg_mode:'6',preserve_interword_spaces:'1'});return worker})),results=new Array(frames.length);let next=0,done=0;try{await Promise.all(workers.map(async worker=>{while(true){const index=next++;if(index>=frames.length)return;const frame=frames[index].canvas,regions=extractCardRegions(frame),cardCandidates=regions.map(region=>({signature:region.signature,features:artworkFeatures(region.canvas)})),cardHashes=regions.map(region=>region.hash),cardResult=await worker.recognize(cardTextSheet(regions)),cardLines=linesFromOcr(cardResult.data,{expand:true});frame.width=frame.height=1;results[index]={time:frames[index].time,lines:recognitionLines(cardLines),cardCandidates,cardHashes};done++;onProgress({phase:`Reading detected card ${done} of ${frames.length}`,value:.14+done/frames.length*.52})}}))}finally{await Promise.all(workers.map(worker=>worker.terminate()))}return results}
async function mapLimit(items,limit,task,onDone=()=>{}){const results=new Array(items.length);let next=0,done=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(true){const index=next++;if(index>=items.length)return;results[index]=await task(items[index],index);onDone(++done,items.length)}}));return results}
function identity(match){return`${match.item.game}|${cardIdentityName(match.item)}`}
function bestByIdentity(rows){const groups=new Map;for(const match of rows){const key=identity(match),group=groups.get(key)||{key,score:0,support:0,rows:[]};group.rows.push(match);group.score=Math.max(group.score,match.score||0);group.support=Math.max(group.support,match.support||0);groups.set(key,group)}return[...groups.values()].sort((a,b)=>b.score-a.score||b.support-a.support)}
export function chooseRecognitionMatches(visual,text){const visualRows=visual||[],textRows=text||[],rankedText=bestByIdentity(textRows),textTop=rankedText[0],textRunner=rankedText[1],textMargin=(textTop?.score||0)-(textRunner?.score||0),strongText=textTop&&textTop.score>=.86&&textMargin>=.08;if(strongText){const agreed=visualRows.filter(match=>identity(match)===textTop.key);return agreed.length?agreed:textTop.rows}if(visualRows.length&&textRows.length){const textKeys=new Set(rankedText.filter(group=>group.score>=.68).map(group=>group.key)),agreed=visualRows.filter(match=>textKeys.has(identity(match)));if(agreed.length)return agreed}if(textTop&&textTop.score>=.68&&textMargin>=.1&&(textTop.rows[0].item.k||textTop.rows[0].item.n).split(' ').length>1)return textTop.rows;const rankedVisual=bestByIdentity(visualRows),top=rankedVisual[0],runner=rankedVisual[1],strongVisual=top&&top.support>=2&&top.score>=.76&&top.score-(runner?.score||0)>=.06;return strongVisual?top.rows:[]}
export async function analyzeVideo(video,{onProgress=()=>{}}={}){
  if(!window.Tesseract)throw new Error('Text recognition could not load. Check the connection and try again.');
  const duration=video.duration;if(!Number.isFinite(duration)||duration<=0)throw new Error('The selected video could not be read.');
  const frames=await selectCandidateFrames(video,duration,onProgress),observations=await recognizeFrames(frames,onProgress),diagnostics=[];
  await mapLimit(observations,4,async row=>{const visual=await matchCardArtwork(row.cardHashes),text=row.lines.length?await matchLines(row.lines.slice(0,60),()=>{},{relaxed:true,candidateMode:true}):[];row.matches=chooseRecognitionMatches(visual,text);row.diagnostic={time:Number(row.time.toFixed(2)),regions:row.cardHashes.length,ocr:row.lines.slice(0,12),visual:visual.slice(0,8).map(x=>({id:x.item.id,game:x.item.game,name:x.item.name||x.item.n,set:x.item.set,distance:x.distance,support:x.support,score:Number((x.score||0).toFixed(3))})),text:text.slice(0,8).map(x=>({id:x.item.id,game:x.item.game,name:x.item.name||x.item.n,set:x.item.set,line:x.line,score:Number((x.score||0).toFixed(3))})),selected:row.matches.slice(0,8).map(x=>({id:x.item.id,game:x.item.game,name:x.item.name||x.item.n,set:x.item.set,score:Number((x.score||0).toFixed(3))}))}},(done,total)=>onProgress({phase:`Matching card artwork ${done} of ${total}`,value:.68+done/total*.2}));
  const detections=[];
  for(let i=0;i<observations.length;i++){
    const row=observations[i],matches=row.matches;
    if(matches[0]){const byIdentity=new Map;for(const match of matches){const key=`${match.item.game}|${cardIdentityName(match.item)}`,prior=byIdentity.get(key);if(!prior||match.score>prior.score)byIdentity.set(key,match)}const ranked=[...byIdentity.values()].sort((a,b)=>b.score-a.score),top=ranked[0],runner=ranked[1],margin=top.score-(runner?.score||0);row.diagnostic.decision={top:`${top.item.game}|${cardIdentityName(top.item)}`,score:Number(top.score.toFixed(3)),margin:Number(margin.toFixed(3)),accepted:top.score>=.66&&(margin>=.04||top.score>=.88)};if(row.diagnostic.decision.accepted){const key=cardIdentityName(top.item),alternatives=matches.filter(x=>x.item.game===top.item.game&&cardIdentityName(x.item)===key).slice(0,16).map(x=>x.item);detections.push({time:row.time,cardCandidates:row.cardCandidates,match:{...top,alternatives}})}}else row.diagnostic.decision={accepted:false,reason:'no identity survived visual/text agreement'};diagnostics.push(row.diagnostic)
  }
  const groups=groupDetections(detections,{allowStrongSingles:true}).filter(g=>(g.match.alternatives||[g.match.item]).some(item=>anyFinishAtLeast(item))),hits=[];
  for(let i=0;i<groups.length;i++){const g=groups[i],textCandidates=g.match.alternatives||[g.match.item],visualMatches=await rerankByCardImage(g.cardCandidates,textCandidates.map(item=>({item,score:g.match.score}))),candidates=visualMatches.map(match=>match.item),chosen=candidates.find(x=>x.vf!=='foil')||candidates[0]||g.match.item,price=priceFor(chosen,'nonfoil'),identityConfidence=visualMatches[0]?.score||g.match.score,identityAmbiguous=new Set(candidates.map(x=>`${x.game}|${x.set}|${x.name}|${x.printing||''}`)).size>1,specialFinishOnly=(price===null||price<1)&&candidates.some(item=>anyFinishAtLeast(item));hits.push({id:crypto.randomUUID(),time:g.time,name:cardIdentityName(chosen).replace(/\b\w/g,c=>c.toUpperCase()),game:chosen.game,set:chosen.set,printing:chosen.printing||'',productId:chosen.id,finish:'nonfoil',finishConfidence:1,foilScore:null,price,identityConfidence,identityAmbiguous,confirmed:identityConfidence>=.9&&!identityAmbiguous&&!specialFinishOnly&&price!==null&&price>=1,skipped:false,candidates});onProgress({phase:`Verifying distinct card ${i+1} of ${groups.length}`,value:.88+(i+1)/Math.max(1,groups.length)*.12})}
  const games=[...new Set(detections.map(row=>row.match.item.game))],selectedGame=games.length===1?games[0]:games.length>1?'Mixed TCGs':null;onProgress({phase:'Analysis complete',value:1});await seek(video,0);return{hits,frames:frames.length,detections:detections.length,selectedGame,selectedSet:null,diagnostics};
}
