import{loadManifest}from'./catalog-client.js';import{analyzeVideo}from'./analyzer.js';
const $=id=>document.getElementById(id),video=$('video'),canvas=$('output'),ctx=canvas.getContext('2d'),logo=$('logo');let videoURL,logoURL,logoReady=false,hits=[],raf,manifest;
const setStep=n=>document.querySelectorAll('.step').forEach((x,i)=>x.className='step '+(i+1<n?'done':i+1===n?'active':''));
function fitCover(sw,sh,x,y,w,h){const r=Math.max(w/sw,h/sh),dw=sw*r,dh=sh*r;return[x+(w-dw)/2,y+(h-dh)/2,dw,dh]}
function fitContain(sw,sh,x,y,w,h){const r=Math.min(w/sw,h/sh),dw=sw*r,dh=sh*r;return[x+(w-dw)/2,y+(h-dh)/2,dw,dh]}
function eligible(h){return!h.skipped&&h.confirmed&&h.finish!=='unknown'&&(h.price===null||h.price>=1)}
function activeHit(t){return hits.find(h=>eligible(h)&&t>=h.time&&t<h.time+3.6)}
function draw(){ctx.fillStyle='#000';ctx.fillRect(0,0,720,1280);const x=16,y=200,w=688,h=955;if(video.readyState>=2){const[dX,dY,dW,dH]=fitContain(video.videoWidth,video.videoHeight,x+14,y+14,w-28,h-28);ctx.drawImage(video,dX,dY,dW,dH)}ctx.strokeStyle='#178dff';ctx.lineWidth=4;ctx.strokeRect(x,y,w,h);ctx.strokeStyle='#5bc0ff';ctx.lineWidth=1;ctx.strokeRect(x+7,y+7,w-14,h-14);const hit=activeHit(video.currentTime||0);if(hit){ctx.textAlign='center';ctx.font='700 27px system-ui';ctx.fillStyle='#e9c66b';ctx.fillText(`${hit.name}${hit.finish==='foil'?' (FOIL)':''}`.toUpperCase().slice(0,42),360,108);ctx.font='800 34px system-ui';ctx.fillStyle='#36df88';ctx.fillText(hit.price===null?'PRICE NOT VERIFIED':`$${Number(hit.price).toFixed(2)}`,360,151);ctx.font='13px system-ui';ctx.fillStyle='#9eabba';ctx.fillText(`${hit.game} • ${hit.set} • TCGPLAYER NM ${hit.finish==='foil'?'FOIL':'NON-FOIL'}${hit.price===null?' • VALUE OMITTED':''}`.toUpperCase().slice(0,82),360,179)}const bx=610,by=1047,br=36;ctx.save();ctx.beginPath();ctx.arc(bx,by,br,0,Math.PI*2);ctx.clip();ctx.fillStyle='#0c1420';ctx.fillRect(bx-br,by-br,br*2,br*2);if(logoReady){const[lx,ly,lw,lh]=fitCover(logo.naturalWidth,logo.naturalHeight,bx-br,by-br,br*2,br*2);ctx.drawImage(logo,lx,ly,lw,lh)}else{ctx.fillStyle='#e9c66b';ctx.font='900 17px system-ui';ctx.textAlign='center';ctx.fillText('TSV',bx,by+6)}ctx.restore();ctx.beginPath();ctx.arc(bx,by,br,0,Math.PI*2);ctx.strokeStyle='#e9c66b';ctx.lineWidth=2;ctx.stroke();if($('showCta').checked){ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='800 20px system-ui';ctx.fillText(($('cta').value.trim()||'FOLLOW FOR MORE LIVE TCG HITS').slice(0,56),360,1195);const seller=$('seller').value.trim();if(seller){ctx.fillStyle='#e9c66b';ctx.font='700 15px system-ui';ctx.fillText(seller,360,1225)}}}
function updateReady(){const ready=!!videoURL&&logoReady&&manifest;$('analyze').disabled=!ready;$('analysisState').textContent=!videoURL?'Choose a Whatnot clip first.':!logoReady?'Add the stream logo.':!manifest?'Waiting for the card catalog.':'Ready to analyze.'}
loadManifest().then(x=>{manifest=x;$('catalogBadge').textContent=`${x.categoryCount} TCG categories • ${new Date(x.generatedAt).toLocaleDateString()}`;$('catalogBadge').classList.add('ready');updateReady()}).catch(e=>{$('catalogBadge').textContent='Catalog setup required';$('catalogBadge').classList.add('error');$('analysisState').textContent=e.message;updateReady()});
$('videoFile').onchange=e=>{const f=e.target.files[0];if(!f)return;if(videoURL)URL.revokeObjectURL(videoURL);videoURL=URL.createObjectURL(f);video.src=videoURL;$('videoLabel').textContent=f.name;video.onloadedmetadata=()=>{$('scrub').max=video.duration;$('playPause').disabled=false;draw();updateReady()}};
$('logoFile').onchange=e=>{const f=e.target.files[0];if(!f)return;if(logoURL)URL.revokeObjectURL(logoURL);logoURL=URL.createObjectURL(f);logo.src=logoURL;$('logoLabel').textContent=f.name;logo.onload=()=>{logoReady=true;draw();updateReady()}};
function marketFor(item,finish){if(!item||finish==='unknown')return null;const rows=item.p||[],usable=item.vf==='foil'?rows:rows.filter(x=>finish==='foil'?String(x.f).toLowerCase().includes('foil'):!String(x.f).toLowerCase().includes('foil')),values=usable.map(x=>Number(x.m)).filter(Number.isFinite);return values.length?Math.max(...values):null}
function applyCandidate(h,item,finish=h.finish){h.productId=item.id;h.name=(item.name||'').replace(/\s*\(foil\)\s*$/i,'');h.game=item.game;h.set=item.set;h.printing=item.printing||'';h.price=marketFor(item,finish)}
function renderHits(){const root=$('hits');root.innerHTML='';const review=hits.filter(h=>!h.skipped&&!h.confirmed);$('reviewSummary').textContent=review.length?`${review.length} match${review.length===1?' needs':'es need'} a quick check. Confident $1+ hits are already ready.`:'Every match passed its confidence checks.';for(const h of hits){const card=document.createElement('div');card.className='hit';const price=h.price===null?'Price unavailable':`$${h.price.toFixed(2)}`;card.innerHTML=`<div class="hit-head"><div><div class="hit-name"></div><div class="hit-meta"></div></div><span class="confidence ${h.confirmed?'ready':''}">${h.skipped?'SKIPPED':h.confirmed?'READY':'CHECK'}</span></div><select class="candidate" aria-label="Card match"></select><div class="choice-row"><button data-finish="foil">Foil</button><button data-finish="nonfoil">Non-foil</button><button data-finish="unknown">Unsure</button></div><div class="choice-row"><button data-action="confirm">Confirm</button><button data-action="jump">View frame</button><button data-action="skip">Skip</button></div>`;card.querySelector('.hit-name').textContent=h.name;card.querySelector('.hit-meta').innerHTML=`${h.game} • ${h.set} • <span class="${h.price===null?'warning':'price'}">${price}</span>`;const sel=card.querySelector('select');for(const c of h.candidates){const o=document.createElement('option');o.textContent=`${c.name} — ${c.set}`;o.value=c.id;o.selected=c.id===h.productId;sel.appendChild(o)}sel.onchange=()=>{const item=h.candidates.find(x=>String(x.id)===sel.value);if(item){applyCandidate(h,item);h.confirmed=false;renderHits();draw()}};card.querySelectorAll('[data-finish]').forEach(b=>{if(b.dataset.finish===h.finish)b.classList.add('selected');b.onclick=()=>{h.finish=b.dataset.finish;const variant=h.candidates.find(x=>h.finish==='foil'?x.vf==='foil':x.vf!=='foil');if(variant)applyCandidate(h,variant,h.finish);else h.price=null;h.confirmed=false;renderHits();draw()}});card.querySelector('[data-action="confirm"]').onclick=()=>{if(h.finish==='unknown')return alert('Choose Foil or Non-foil before confirming.');h.confirmed=true;renderHits();draw();enableExport()};card.querySelector('[data-action="jump"]').onclick=()=>{video.currentTime=h.time;draw()};card.querySelector('[data-action="skip"]').onclick=()=>{h.skipped=true;h.confirmed=false;renderHits();draw();enableExport()};root.appendChild(card)}}
function enableExport(){const unresolved=hits.some(h=>!h.skipped&&!h.confirmed);$('preview').disabled=unresolved;$('export').disabled=unresolved;$('exportState').textContent=unresolved?'Review the uncertain matches to continue.':`${hits.filter(eligible).length} qualifying hit${hits.filter(eligible).length===1?'':'s'} ready to render.`}
$('analyze').onclick=async()=>{setStep(2);$('analyze').disabled=true;$('progressWrap').hidden=false;$('analysisState').className='state';try{hits=[];const result=await analyzeVideo(video,{onProgress:p=>{const n=Math.round(p.value*100);$('progressBar').style.width=n+'%';$('progressText').textContent=n+'%';$('analysisState').textContent=p.phase}});hits=result.hits;renderHits();$('reviewPanel').hidden=false;setStep(3);const unresolved=hits.filter(h=>!h.confirmed).length,game=result.selectedGame?` Detected ${result.selectedGame}.`:'';$('analysisState').className=hits.length?'state success':'state error';$('analysisState').textContent=hits.length?`Analyzed ${result.frames} frames.${game} Found ${hits.length} card reveal${hits.length===1?'':'s'}${unresolved?`; ${unresolved} need a quick check.`:'.'}`:`Analyzed ${result.frames} frames.${game} No reliable catalog matches were found; do not export this result.`;enableExport()}catch(e){$('analysisState').className='state error';$('analysisState').textContent=e.message||'Analysis failed. Please try again.'}finally{$('progressWrap').hidden=true;$('analyze').disabled=false}};
function clock(t){const m=Math.floor(t/60),s=(t-m*60).toFixed(1).padStart(4,'0');return`${m}:${s}`}
video.ontimeupdate=()=>{$('scrub').value=video.currentTime;$('clock').textContent=clock(video.currentTime);draw()};$('scrub').oninput=e=>video.currentTime=Number(e.target.value);$('playPause').onclick=()=>video.paused?video.play():video.pause();['seller','cta','showCta'].forEach(id=>$(id).oninput=draw);
function loop(){draw();if(!video.paused)raf=requestAnimationFrame(loop)}$('preview').onclick=()=>{setStep(4);video.currentTime=0;video.play();cancelAnimationFrame(raf);loop()};
$('export').onclick=async()=>{setStep(4);$('export').disabled=true;const stream=canvas.captureStream(30),source=video.captureStream?.()||video.mozCaptureStream?.();source?.getAudioTracks().forEach(t=>stream.addTrack(t));const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')?'video/webm;codecs=vp9,opus':'video/webm',rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:6e6}),chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{const url=URL.createObjectURL(new Blob(chunks,{type:mime})),a=document.createElement('a');a.href=url;a.download='TCG_Seller_Vault_Show_Repurposer.webm';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);$('exportState').textContent='Export complete.';$('export').disabled=false};video.currentTime=0;await new Promise(r=>video.addEventListener('seeked',r,{once:true}));rec.start();await video.play();loop();$('exportState').textContent='Rendering… keep this tab open.';video.onended=()=>rec.state!=='inactive'&&rec.stop()};draw();
