import{loadManifest}from'./catalog-client.js?v=24';import{analyzeVideo}from'./analyzer.js?v=24';
const $=id=>document.getElementById(id),video=$('video'),canvas=$('output'),ctx=canvas.getContext('2d',{alpha:false}),logo=$('logo');let videoFile,videoURL,logoURL,logoReady=false,hits=[],raf,frameCallback,manifest;
const setStep=n=>document.querySelectorAll('.step').forEach((x,i)=>x.className='step '+(i+1<n?'done':i+1===n?'active':''));
function fitCover(sw,sh,x,y,w,h){const r=Math.max(w/sw,h/sh),dw=sw*r,dh=sh*r;return[x+(w-dw)/2,y+(h-dh)/2,dw,dh]}
function fitContain(sw,sh,x,y,w,h){const r=Math.min(w/sw,h/sh),dw=sw*r,dh=sh*r;return[x+(w-dw)/2,y+(h-dh)/2,dw,dh]}
// The approved V11 renderer works from the stream viewport, not the full
// phone recording. Whatnot share recordings taller than 2:1 place that
// viewport at this stable normalized rectangle.
function streamViewport(sw,sh){return sh/sw>2?[sw*.18,sh*.154,sw*.64,sh*.537]:[0,0,sw,sh]}
function drawApprovedV11Source(x,y,w,h){
  const[sx,sy,sw,sh]=streamViewport(video.videoWidth,video.videoHeight);
  const scale=Math.min(w/sw,h/sh),dw=sw*scale,dh=sh*scale;
  const dx=x+(w-dw)/2,dy=y+(h-dh)/2;
  ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();
  ctx.drawImage(video,sx,sy,sw,sh,dx,dy,dw,dh);ctx.restore();
}
function eligible(h){return!h.skipped&&h.confirmed&&h.finish!=='unknown'&&(h.price===null||h.price>=1)}
function activeHit(t){return hits.find(h=>eligible(h)&&t>=h.time&&t<h.time+3.6)}
function draw(){ctx.fillStyle='#000';ctx.fillRect(0,0,360,640);const x=12,y=92,w=336,h=510;if(video.readyState>=2)drawApprovedV11Source(x+2,y+2,w-4,h-4);ctx.strokeStyle='#178dff';ctx.lineWidth=2;ctx.strokeRect(x,y,w,h);ctx.strokeStyle='#5bc0ff';ctx.lineWidth=.75;ctx.strokeRect(x+2,y+2,w-4,h-4);const hit=activeHit(video.currentTime||0);if(hit){ctx.textAlign='center';ctx.font='700 14px system-ui';ctx.fillStyle='#e9c66b';ctx.fillText(`${hit.name}${hit.finish==='foil'?' (FOIL)':''}`.toUpperCase().slice(0,42),180,28);ctx.font='800 19px system-ui';ctx.fillStyle='#36df88';ctx.fillText(hit.price===null?'PRICE NOT VERIFIED':`$${Number(hit.price).toFixed(2)}`,180,50);ctx.font='7px system-ui';ctx.fillStyle='#9eabba';ctx.fillText(`${hit.game} • ${hit.set} • TCGPLAYER NM ${hit.finish==='foil'?'FOIL':'NON-FOIL'}${hit.price===null?' • VALUE OMITTED':''}`.toUpperCase().slice(0,82),180,67)}const br=Number($('logoSize').value)/2,bx=Math.max(br,Math.min(360-br,Number($('logoX').value))),by=Math.max(br,Math.min(640-br,Number($('logoY').value)));ctx.save();ctx.beginPath();ctx.arc(bx,by,br,0,Math.PI*2);ctx.clip();ctx.fillStyle='#0c1420';ctx.fillRect(bx-br,by-br,br*2,br*2);if(logoReady){const[lx,ly,lw,lh]=fitCover(logo.naturalWidth,logo.naturalHeight,bx-br,by-br,br*2,br*2);ctx.drawImage(logo,lx,ly,lw,lh)}else{ctx.fillStyle='#e9c66b';ctx.font='900 7px system-ui';ctx.textAlign='center';ctx.fillText('TSV',bx,by+2)}ctx.restore();ctx.beginPath();ctx.arc(bx,by,br,0,Math.PI*2);ctx.strokeStyle='#e9c66b';ctx.lineWidth=1;ctx.stroke();if($('showCta').checked){ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='500 9px system-ui';ctx.fillText(($('cta').value.trim()||'FOLLOW FOR MORE LIVE TCG HITS').slice(0,56),180,617);const seller=$('seller').value.trim();if(seller){ctx.fillStyle='#e9c66b';ctx.font='700 7px system-ui';ctx.fillText(seller,180,631)}}}
function updateReady(){const ready=!!videoURL&&logoReady&&manifest;$('analyze').disabled=!ready;$('analysisState').textContent=!videoURL?'Import a stream clip first.':!logoReady?'Add the stream logo.':!manifest?'Waiting for the card catalog.':'Ready to analyze.'}
loadManifest().then(x=>{manifest=x;$('catalogBadge').textContent=`${x.categoryCount} TCG categories • ${new Date(x.generatedAt).toLocaleDateString()}`;$('catalogBadge').classList.add('ready');updateReady()}).catch(e=>{$('catalogBadge').textContent='Catalog setup required';$('catalogBadge').classList.add('error');$('analysisState').textContent=e.message;updateReady()});
$('videoFile').onchange=e=>{const f=e.target.files[0];if(!f)return;videoFile=f;if(videoURL)URL.revokeObjectURL(videoURL);videoURL=URL.createObjectURL(f);video.src=videoURL;$('videoLabel').textContent=f.name;video.onloadedmetadata=()=>{$('scrub').max=video.duration;$('playPause').disabled=false;draw();updateReady()};video.oncanplay=draw};
$('logoFile').onchange=e=>{const f=e.target.files[0];if(!f)return;if(logoURL)URL.revokeObjectURL(logoURL);logoURL=URL.createObjectURL(f);logo.src=logoURL;$('logoLabel').textContent=f.name;logo.onload=()=>{logoReady=true;draw();updateReady()}};
function marketFor(item,finish){if(!item||finish==='unknown')return null;const rows=item.p||[],usable=item.vf==='foil'?rows:rows.filter(x=>finish==='foil'?String(x.f).toLowerCase().includes('foil'):!String(x.f).toLowerCase().includes('foil')),values=usable.map(x=>Number(x.m)).filter(Number.isFinite);return values.length?Math.max(...values):null}
function applyCandidate(h,item,finish=h.finish){h.productId=item.id;h.name=(item.name||'').replace(/\s*\(foil\)\s*$/i,'');h.game=item.game;h.set=item.set;h.printing=item.printing||'';h.price=marketFor(item,finish)}
function renderHits(){const root=$('hits');root.innerHTML='';const review=hits.filter(h=>!h.skipped&&!h.confirmed);$('reviewSummary').textContent=review.length?`${review.length} match${review.length===1?' needs':'es need'} a quick check. Confident $1+ hits are already ready.`:'Every match passed its confidence checks.';for(const h of hits){const card=document.createElement('div');card.className='hit';const price=h.price===null?'Price unavailable':`$${h.price.toFixed(2)}`;card.innerHTML=`<div class="hit-head"><div><div class="hit-name"></div><div class="hit-meta"></div></div><span class="confidence ${h.confirmed?'ready':''}">${h.skipped?'SKIPPED':h.confirmed?'READY':'CHECK'}</span></div><select class="candidate" aria-label="Card match"></select><div class="choice-row"><button data-finish="foil">Foil</button><button data-finish="nonfoil">Non-foil</button><button data-finish="unknown">Unsure</button></div><div class="choice-row"><button data-action="confirm">Confirm</button><button data-action="jump">View frame</button><button data-action="skip">Skip</button></div>`;card.querySelector('.hit-name').textContent=h.name;card.querySelector('.hit-meta').innerHTML=`${h.game} • ${h.set} • <span class="${h.price===null?'warning':'price'}">${price}</span>`;const sel=card.querySelector('select');for(const c of h.candidates){const o=document.createElement('option');o.textContent=`${c.name} — ${c.set}`;o.value=c.id;o.selected=c.id===h.productId;sel.appendChild(o)}sel.onchange=()=>{const item=h.candidates.find(x=>String(x.id)===sel.value);if(item){applyCandidate(h,item);h.confirmed=false;renderHits();draw()}};card.querySelectorAll('[data-finish]').forEach(b=>{if(b.dataset.finish===h.finish)b.classList.add('selected');b.onclick=()=>{h.finish=b.dataset.finish;const variant=h.candidates.find(x=>h.finish==='foil'?x.vf==='foil':x.vf!=='foil');if(variant)applyCandidate(h,variant,h.finish);else h.price=null;h.confirmed=false;renderHits();draw()}});card.querySelector('[data-action="confirm"]').onclick=()=>{if(h.finish==='unknown')return alert('Choose Foil or Non-foil before confirming.');h.confirmed=true;renderHits();draw();enableExport()};card.querySelector('[data-action="jump"]').onclick=()=>{video.currentTime=h.time;draw()};card.querySelector('[data-action="skip"]').onclick=()=>{h.skipped=true;h.confirmed=false;renderHits();draw();enableExport()};root.appendChild(card)}}
function enableExport(){const unresolved=hits.some(h=>!h.skipped&&!h.confirmed);$('preview').disabled=unresolved;$('export').disabled=unresolved;$('exportState').textContent=unresolved?'Review the uncertain matches to continue.':`${hits.filter(eligible).length} qualifying hit${hits.filter(eligible).length===1?'':'s'} ready to render.`}
$('analyze').onclick=async()=>{setStep(2);$('analyze').disabled=true;$('progressWrap').hidden=false;$('analysisState').className='state';try{hits=[];const result=await analyzeVideo(video,{onProgress:p=>{const n=Math.round(p.value*100);$('progressBar').style.width=n+'%';$('progressText').textContent=n+'%';$('analysisState').textContent=p.phase}});hits=result.hits;renderHits();$('reviewPanel').hidden=false;setStep(3);const unresolved=hits.filter(h=>!h.confirmed).length,game=result.selectedGame?` Detected ${result.selectedGame}.`:'';$('analysisState').className=hits.length?'state success':'state error';$('analysisState').textContent=hits.length?`Analyzed ${result.frames} frames.${game} Found ${hits.length} card reveal${hits.length===1?'':'s'}${unresolved?`; ${unresolved} need a quick check.`:'.'}`:`Analyzed ${result.frames} frames.${game} No reliable catalog matches were found; do not export this result.`;enableExport()}catch(e){$('analysisState').className='state error';$('analysisState').textContent=e.message||'Analysis failed. Please try again.'}finally{$('progressWrap').hidden=true;$('analyze').disabled=false}};
function clock(t){const m=Math.floor(t/60),s=(t-m*60).toFixed(1).padStart(4,'0');return`${m}:${s}`}
video.ontimeupdate=()=>{$('scrub').value=video.currentTime;$('clock').textContent=clock(video.currentTime);draw()};$('scrub').oninput=e=>video.currentTime=Number(e.target.value);$('playPause').onclick=()=>video.paused?video.play():video.pause();['seller','cta','showCta','logoX','logoY','logoSize'].forEach(id=>$(id).oninput=()=>{const out=$(id+'Value');if(out)out.value=$(id).value;draw()});
function stopRenderLoop(){cancelAnimationFrame(raf);if(frameCallback&&video.cancelVideoFrameCallback)video.cancelVideoFrameCallback(frameCallback);frameCallback=0}
function loop(){draw();if(video.paused||video.ended)return;if(video.requestVideoFrameCallback)frameCallback=video.requestVideoFrameCallback(loop);else raf=requestAnimationFrame(loop)}
$('preview').onclick=async()=>{setStep(4);stopRenderLoop();video.currentTime=0;await video.play();loop()};
function pngBytes(layer){return new Promise((resolve,reject)=>layer.toBlob(async b=>b?resolve(new Uint8Array(await b.arrayBuffer())):reject(new Error('Could not create video overlay.')),'image/png'))}
function overlayCanvas(hit=null){const layer=document.createElement('canvas');layer.width=360;layer.height=640;const c=layer.getContext('2d');if(hit){c.textAlign='center';c.font='700 14px system-ui';c.fillStyle='#e9c66b';c.fillText((hit.name+(hit.finish==='foil'?' (FOIL)':'')).toUpperCase().slice(0,42),180,28);c.font='800 19px system-ui';c.fillStyle='#36df88';c.fillText(hit.price===null?'PRICE NOT VERIFIED':String.fromCharCode(36)+Number(hit.price).toFixed(2),180,50);c.font='7px system-ui';c.fillStyle='#9eabba';c.fillText((hit.game+' • '+hit.set+' • TCGPLAYER NM '+(hit.finish==='foil'?'FOIL':'NON-FOIL')+(hit.price===null?' • VALUE OMITTED':'')).toUpperCase().slice(0,82),180,67);return layer}c.strokeStyle='#178dff';c.lineWidth=2;c.strokeRect(12,92,336,510);c.strokeStyle='#5bc0ff';c.lineWidth=.75;c.strokeRect(14,94,332,506);const br=Number($('logoSize').value)/2,bx=Math.max(br,Math.min(360-br,Number($('logoX').value))),by=Math.max(br,Math.min(640-br,Number($('logoY').value)));c.save();c.beginPath();c.arc(bx,by,br,0,Math.PI*2);c.clip();c.fillStyle='#0c1420';c.fillRect(bx-br,by-br,br*2,br*2);if(logoReady){const[lx,ly,lw,lh]=fitCover(logo.naturalWidth,logo.naturalHeight,bx-br,by-br,br*2,br*2);c.drawImage(logo,lx,ly,lw,lh)}c.restore();c.beginPath();c.arc(bx,by,br,0,Math.PI*2);c.strokeStyle='#e9c66b';c.lineWidth=1;c.stroke();if($('showCta').checked){c.textAlign='center';c.fillStyle='#fff';c.font='500 9px system-ui';c.fillText(($('cta').value.trim()||'FOLLOW FOR MORE LIVE TCG HITS').slice(0,56),180,617);const seller=$('seller').value.trim();if(seller){c.fillStyle='#e9c66b';c.font='700 7px system-ui';c.fillText(seller,180,631)}}return layer}
let ffmpeg;
async function loadFfmpeg(){if(ffmpeg)return ffmpeg;if(!window.FFmpeg)throw new Error('The video renderer did not load. Check your connection and try again.');ffmpeg=window.FFmpeg.createFFmpeg({log:false,corePath:'https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.11.0/dist/ffmpeg-core.js'});ffmpeg.setProgress(({ratio})=>{$('exportState').textContent='Rendering full-quality video… '+Math.min(99,Math.max(0,Math.round(ratio*100)))+'%'});await ffmpeg.load();return ffmpeg}
$('export').onclick=async()=>{setStep(4);$('export').disabled=true;stopRenderLoop();video.pause();$('exportState').textContent='Preparing full-quality renderer…';const files=[];try{const engine=await loadFfmpeg(),ext=(videoFile.name.split('.').pop()||'mp4').replace(/[^a-z0-9]/gi,'').toLowerCase(),source='source.'+ext;engine.FS('writeFile',source,new Uint8Array(await videoFile.arrayBuffer()));files.push(source);const bg=document.createElement('canvas');bg.width=360;bg.height=640;const bc=bg.getContext('2d');bc.fillStyle='#000';bc.fillRect(0,0,360,640);engine.FS('writeFile','background.png',await pngBytes(bg));engine.FS('writeFile','decor.png',await pngBytes(overlayCanvas()));files.push('background.png','decor.png');const qualifying=hits.filter(eligible),args=['-loop','1','-i','background.png','-i',source,'-loop','1','-i','decor.png'];for(let i=0;i<qualifying.length;i++){const name='hit'+i+'.png';engine.FS('writeFile',name,await pngBytes(overlayCanvas(qualifying[i])));files.push(name);args.push('-loop','1','-i',name)}let sourceFilter="crop=w='if(gt(ih/iw,2),iw*.64,iw)':h='if(gt(ih/iw,2),ih*.537,ih)':x='if(gt(ih/iw,2),iw*.18,0)':y='if(gt(ih/iw,2),ih*.154,0)',scale=332:506:force_original_aspect_ratio=decrease,pad=332:506:(ow-iw)/2:(oh-ih)/2:black";let filter='[1:v]'+sourceFilter+'[clip];[0:v][clip]overlay=14:94[base];[base][2:v]overlay=0:0[v2]',last='v2';qualifying.forEach((h,i)=>{const next='v'+(i+3);filter+=";["+last+"]["+(i+3)+":v]overlay=0:0:enable='between(t,"+Math.max(0,h.time).toFixed(3)+","+Math.min(video.duration,h.time+3.6).toFixed(3)+")'["+next+"]";last=next});args.push('-filter_complex',filter,'-map','['+last+']','-map','1:a?','-t',String(video.duration),'-r','24','-c:v','libx264','-preset','ultrafast','-crf','23','-pix_fmt','yuv420p','-c:a','aac','-b:a','128k','-movflags','+faststart','output.mp4');await engine.run(...args);const data=engine.FS('readFile','output.mp4'),url=URL.createObjectURL(new Blob([data.buffer],{type:'video/mp4'})),a=document.createElement('a');a.href=url;a.download='TCG_Seller_Vault_Show_Repurposer.mp4';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);files.push('output.mp4');$('exportState').textContent='Export complete — every source frame was rendered.'}catch(e){console.error(e);$('exportState').textContent=e.message||'Export failed. Please try again.'}finally{if(ffmpeg)for(const name of files)try{ffmpeg.FS('unlink',name)}catch{}$('export').disabled=false;draw()}};draw();
