import{differenceHash,hashBands,hashDistance}from'./visual-hash.js?v=1';
import{artworkFeatures,featureMatches}from'./feature-matcher.js?v=1';
const imageCache=new Map,visualFileCache=new Map,itemBucketCache=new Map;

function cropCanvas(source,x,y,w,h,width=240){const out=document.createElement('canvas'),height=Math.max(1,Math.round(width*h/w));out.width=width;out.height=height;out.getContext('2d',{willReadFrequently:true}).drawImage(source,x,y,w,h,0,0,width,height);return out}
function expandedCrop(source,x,y,w,h,width=360){const padX=w*.22,padY=h*.1,left=Math.max(0,x-padX),top=Math.max(0,y-padY),right=Math.min(source.width,x+w+padX),bottom=Math.min(source.height,y+h+padY);return cropCanvas(source,left,top,right-left,bottom-top,width)}
function rectSum(integral,stride,x,y,w,h){const a=y*stride+x,b=y*stride+x+w,c=(y+h)*stride+x,d=(y+h)*stride+x+w;return integral[d]-integral[b]-integral[c]+integral[a]}
function overlap(a,b){const area=Math.max(0,Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y));return area/(a.w*a.h+b.w*b.h-area||1)}
function signature(source){const canvas=document.createElement('canvas');canvas.width=24;canvas.height=34;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(source,0,0,canvas.width,canvas.height);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height).data,luma=new Float32Array(canvas.width*canvas.height),edge=new Float32Array(luma.length);let total=0;for(let i=0,p=0;i<pixels.length;i+=4,p++){const value=pixels[i]*.299+pixels[i+1]*.587+pixels[i+2]*.114;luma[p]=value;total+=value}const mean=total/luma.length;let norm=0;for(let i=0;i<luma.length;i++){luma[i]-=mean;norm+=luma[i]*luma[i]}norm=Math.sqrt(norm)||1;for(let i=0;i<luma.length;i++)luma[i]/=norm;for(let y=1;y<canvas.height-1;y++)for(let x=1;x<canvas.width-1;x++){const i=y*canvas.width+x;edge[i]=Math.abs(luma[i+1]-luma[i-1])+Math.abs(luma[i+canvas.width]-luma[i-canvas.width])}return{luma,edge}}
function artworkHash(source){const canvas=document.createElement('canvas');canvas.width=9;canvas.height=8;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(source,0,0,9,8);const pixels=ctx.getImageData(0,0,9,8).data,gray=new Uint8Array(72);for(let i=0,p=0;i<pixels.length;i+=4,p++)gray[p]=Math.round(pixels[i]*.299+pixels[i+1]*.587+pixels[i+2]*.114);return differenceHash(gray)}
function similarity(a,b){let lum=0,edgeMin=0,edgeMax=0;for(let i=0;i<a.luma.length;i++){lum+=a.luma[i]*b.luma[i];edgeMin+=Math.min(a.edge[i],b.edge[i]);edgeMax+=Math.max(a.edge[i],b.edge[i])}const edge=edgeMax?edgeMin/edgeMax:0;return Math.max(0,Math.min(1,(lum+1)*.36+edge*.28))}

export function extractCardRegions(frame){const portrait=frame.height>frame.width,x0=Math.round(frame.width*(portrait?.08:.04)),y0=Math.round(frame.height*(portrait?.08:.04)),w0=Math.round(frame.width*(portrait?.84:.92)),h0=Math.round(frame.height*(portrait?.62:.9)),roi=cropCanvas(frame,x0,y0,w0,h0,240),ctx=roi.getContext('2d',{willReadFrequently:true}),data=ctx.getImageData(0,0,roi.width,roi.height).data,gray=new Float32Array(roi.width*roi.height),edge=new Float32Array(gray.length);for(let i=0,p=0;i<data.length;i+=4,p++)gray[p]=data[i]*.299+data[i+1]*.587+data[i+2]*.114;for(let y=1;y<roi.height-1;y++)for(let x=1;x<roi.width-1;x++){const i=y*roi.width+x;edge[i]=Math.min(255,Math.abs(gray[i+1]-gray[i-1])+Math.abs(gray[i+roi.width]-gray[i-roi.width]))}const stride=roi.width+1,integral=new Float64Array((roi.height+1)*stride);for(let y=0;y<roi.height;y++){let row=0;for(let x=0;x<roi.width;x++){row+=edge[y*roi.width+x];integral[(y+1)*stride+x+1]=integral[y*stride+x+1]+row}}const scored=[];for(let width=40;width<=120;width+=8)for(const aspect of[1.35,1.45,1.55,1.65,1.9,2.2]){const height=Math.round(width*aspect);if(height>=roi.height-4)continue;const inset=Math.max(3,Math.floor(width/18));for(let y=2;y<roi.height-height-2;y+=6)for(let x=2;x<roi.width-width-2;x+=6){const outer=rectSum(integral,stride,x,y,width,height),inner=rectSum(integral,stride,x+inset,y+inset,width-inset*2,height-inset*2),border=(outer-inner)/(width*height-(width-inset*2)*(height-inset*2)),inside=inner/((width-inset*2)*(height-inset*2)),cx=x+width/2,cy=y+height/2,center=1-Math.hypot((cx-roi.width/2)/roi.width,(cy-roi.height*.42)/roi.height),size=Math.min(1,width/68),cardShape=height/width>=1.35&&height/width<=2.2?6:0;scored.push({x,y,w:width,h:height,score:border*1.1+inside*.25+center*18+size*18+cardShape})}}scored.sort((a,b)=>b.score-a.score);const chosen=[];for(const rect of scored){if(chosen.every(other=>overlap(rect,other)<.45))chosen.push(rect);if(chosen.length===8)break}const scale=w0/roi.width;return chosen.map(rect=>{const x=x0+rect.x*scale,y=y0+rect.y*scale,w=rect.w*scale,h=rect.h*scale,canvas=expandedCrop(frame,x,y,w,h);return{canvas,signature:signature(canvas),hash:artworkHash(canvas),score:rect.score,bounds:{x,y,w,h}}})}
export function extractCardCandidates(frame){return extractCardRegions(frame).map(region=>region.signature)}

async function visualFile(path,cache){if(!cache.has(path))cache.set(path,fetch(`./catalog/visual/${path}`).then(r=>r.ok?r.json():[]).catch(()=>[]));return cache.get(path)}
async function visualItem(id){const bucket=(Number(id)%64).toString(16).padStart(2,'0'),items=await visualFile(`items/${bucket}.json`,itemBucketCache);return items.find(item=>String(item.id)===String(id))||null}
export async function matchCardArtwork(hashes,limit=20){const unique=[...new Set((hashes||[]).filter(hash=>/^[0-9a-f]{16}$/i.test(hash)))],ranked=new Map;for(const hash of unique){const lists=await Promise.all(hashBands(hash).map((key,index)=>visualFile(`bands/${index}-${key}.json`,visualFileCache))),seenForHash=new Map;for(const[reference,id]of lists.flat()){const distance=hashDistance(hash,reference),key=String(id),prior=seenForHash.get(key);if(distance<=26&&(!prior||distance<prior.distance))seenForHash.set(key,{distance,hash:reference})}for(const[id,row]of seenForHash){const prior=ranked.get(id);if(prior){prior.support++;if(row.distance<prior.distance){prior.distance=row.distance;prior.hash=row.hash}}else ranked.set(id,{...row,support:1})}}const nearest=[...ranked.entries()].sort((a,b)=>b[1].support-a[1].support||a[1].distance-b[1].distance).slice(0,limit),items=await Promise.all(nearest.map(([id])=>visualItem(id)));return nearest.map(([id,row],index)=>items[index]?{item:items[index],score:Math.max(0,1-row.distance/64)*Math.min(1,.72+row.support*.14),visualScore:Math.max(0,1-row.distance/64),distance:row.distance,support:row.support}:null).filter(Boolean)}

async function referenceSignature(id){if(imageCache.has(id))return imageCache.get(id);const promise=(async()=>{const controller=new AbortController,timeout=setTimeout(()=>controller.abort(),5000);try{const response=await fetch(`https://tcgplayer-cdn.tcgplayer.com/product/${id}_in_400x400.jpg`,{signal:controller.signal,mode:'cors'});if(!response.ok)return null;const bitmap=await createImageBitmap(await response.blob()),canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d',{willReadFrequently:true}).drawImage(bitmap,0,0);bitmap.close();return{signature:signature(canvas),features:artworkFeatures(canvas)}}catch{return null}finally{clearTimeout(timeout)}})();imageCache.set(id,promise);return promise}

export async function rerankByCardImage(cardCandidates,matches){if(!cardCandidates?.length||!matches?.length)return matches;const shortlist=[],seen=new Set;for(const match of matches){const id=String(match.item.id);if(seen.has(id))continue;seen.add(id);shortlist.push(match);if(shortlist.length===16)break}await Promise.all(shortlist.map(async match=>{const reference=await referenceSignature(match.item.id);if(!reference)return;match.visualScore=Math.max(...cardCandidates.map(candidate=>similarity(candidate.signature,reference.signature)));match.featureMatches=Math.max(0,...cardCandidates.map(candidate=>featureMatches(reference.features,candidate.features)))}));const strongest=Math.max(0,...shortlist.map(match=>match.featureMatches||0));if(strongest>=6){for(const match of shortlist){const featureScore=Math.min(1,(match.featureMatches||0)/24);match.score=Math.min(.99,match.score*.35+featureScore*.65)}return matches.sort((a,b)=>(b.featureMatches||0)-(a.featureMatches||0)||b.score-a.score)}const visualStrongest=Math.max(0,...shortlist.map(match=>match.visualScore||0));if(visualStrongest<.55)return matches;for(const match of shortlist)if(Number.isFinite(match.visualScore))match.score=Math.min(.99,match.score*.78+match.visualScore*.22);return matches.sort((a,b)=>b.score-a.score)}
