const cache=new Map();
export function normalize(value){return String(value||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function editDistance(a,b){const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const hold=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=hold}}return row[b.length]}
function similarity(a,b){if(!a||!b)return 0;if(a===b)return 1;if(a.includes(b)||b.includes(a))return Math.min(a.length,b.length)/Math.max(a.length,b.length)*.92;return 1-editDistance(a,b)/Math.max(a.length,b.length)}
const STOP=new Set(['a','an','and','at','by','for','from','in','of','on','the','to','with']);
export function tokenSimilarity(line,key){const words=line.split(' ').filter(Boolean),wanted=key.split(' ').filter(w=>w.length>2&&!STOP.has(w));if(!wanted.length)return 0;const scores=wanted.map(word=>Math.max(0,...words.map(candidate=>similarity(candidate,word))));const strong=scores.filter(score=>score>=.78).length;if(!strong)return 0;const coverage=scores.reduce((sum,score)=>sum+score,0)/scores.length;return Math.min(.93,coverage*.72+(strong/wanted.length)*.28)}
export async function loadManifest(){const r=await fetch('./catalog/manifest.json',{cache:'no-cache'});if(!r.ok)throw new Error('Card catalog has not been built yet.');return r.json()}
async function loadShard(prefix){if(cache.has(prefix))return cache.get(prefix);const promise=fetch(`./catalog/shards/${prefix}.json`).then(r=>r.ok?r.json():[]).catch(()=>[]);cache.set(prefix,promise);return promise}
export async function matchLines(lines,onProgress=()=>{},{game=null,set=null,relaxed=false}={}){const cleaned=[...new Set(lines.map(normalize).filter(x=>x.length>=4&&x.length<=72&&/[a-z]{3}/.test(x)&&x.split(' ').length<=12))];const best=new Map;for(let i=0;i<cleaned.length;i++){const line=cleaned[i],words=line.split(' '),prefixes=new Set([line.slice(0,2),...words.filter(w=>w.length>2).map(w=>w.slice(0,2))]);const shards=(await Promise.all([...prefixes].map(loadShard))).flat();for(const item of shards){if(game&&item.game!==game)continue;if(set&&item.set!==set)continue;const key=item.k||item.n,keyWords=key.split(' '),windows=[...words.map((_,start)=>words.slice(start,start+keyWords.length).join(' ')),...words.map((_,start)=>words.slice(start,start+keyWords.length+1).join(' '))],score=Math.max(similarity(line,key),...windows.map(part=>similarity(part,key)),relaxed?tokenSimilarity(line,key):0),threshold=keyWords.length===1?(relaxed?.9:.94):(relaxed?.5:.84);if(score>=threshold){const id=String(item.id),prior=best.get(id);if(!prior||score>prior.score)best.set(id,{item,score,line})}}onProgress((i+1)/Math.max(1,cleaned.length))}return[...best.values()].sort((a,b)=>b.score-a.score)}
